"""Compose multi-paragraph synthetic chunks from hand-written fragments.

Phase 2 subagents will hand-write atomic fragments (greetings, body
paragraphs, signatures, document fields). Each fragment uses a simple
**marker syntax** like ``[[PII:phone]]`` to mark where a PII value
should go. This module:

1. Generates a PII value for each marker (via :mod:`pii_values` and
   :mod:`name_registry`).
2. Substitutes the marker with the value, tracking the resulting
   character offsets.
3. Emits a :class:`schema.Chunk` with correct, validated spans.

Why markers instead of `{name}`-style format strings: format-string
substitution can't track where the substituted value ends up if the
value itself contains characters that look like format spec. Markers
are unambiguous and parse trivially.

Marker syntax:

    [[PII:short_label]]                 — generic, generator picks format
    [[PII:short_label/fmt_hint]]         — pin a specific format

Short labels (mapped to label_space.CATEGORIES):
    person, address, date, email, phone, url, account, secret
Plus structural ones (also map to private_person):
    first, last, full, title_last, title_first_last, last_first,
    last_first_upper, first_initial

A single fragment also gets a per-fragment language context — all PII
values are generated to match the fragment's language (e.g., a DE
fragment produces de_ch addresses + DE month names in dates).
"""
from __future__ import annotations

import random
import re
import uuid
from collections.abc import Iterator
from dataclasses import dataclass, field
from typing import Literal

from . import name_registry as _nr
from . import pii_values as _pv
from .schema import Chunk, Span

# Marker syntax: [[PII:label]] or [[PII:label/fmt]]
_MARKER_RE = re.compile(r"\[\[PII:([a-z_]+)(?:/([a-z_0-9]+))?\]\]")


# Short-label → canonical category mapping.
_LABEL_MAP = {
    "person":  "private_person",
    "first":   "private_person",
    "last":    "private_person",
    "full":    "private_person",
    "title_last":         "private_person",
    "title_first_last":   "private_person",
    "title_initial_last": "private_person",
    "last_first":         "private_person",
    "last_first_upper":   "private_person",
    "first_initial":      "private_person",
    "common_last":        "private_person",
    "address": "private_address",
    "date":    "private_date",
    "email":   "private_email",
    "phone":   "private_phone",
    "url":     "private_url",
    "account": "account_number",
    "iban":    "account_number",
    "ahv":     "account_number",
    "vat":     "account_number",
    "cc":      "account_number",
    "secret":  "secret",
}


@dataclass(slots=True)
class Fragment:
    """One hand-written text fragment with PII markers.

    Subagents in Phase 2 will write lists of these. Each fragment must
    be SHORT (one sentence to one paragraph) and hand-typed (not
    generated by a loop or regex).

    Fields:
      template_id : stable id for tracking which template a chunk came from
      language    : "de_ch" / "fr_ch" / "it_ch" / "rm" / "en"
      text        : the fragment body, with [[PII:label]] markers
      meta        : optional info (gender for title-bearing fragments, etc.)
    """
    template_id: str
    language: str
    text: str
    meta: dict = field(default_factory=dict)


def _gen_for_marker(short_label: str, fmt_hint: str | None,
                    language: str, gender: Literal["m", "f"],
                    rng: random.Random) -> str:
    """Generate one PII value for the given marker."""
    # Person variants — delegate to name_registry
    if short_label == "first":
        return _nr.first_name(language, rng)
    if short_label == "last":
        return _nr.last_name(language, rng)
    if short_label == "common_last":
        return _nr.common_word_lastname(language, rng)
    if short_label == "full" or short_label == "person":
        return _nr.full_name(language, rng)
    if short_label == "title_last":
        return _nr.format_name(
            _nr.first_name(language, rng), _nr.last_name(language, rng),
            "title_last", language=language, gender=gender,
            title_style=fmt_hint or "auto", rng=rng,
        )
    if short_label == "title_first_last":
        return _nr.format_name(
            _nr.first_name(language, rng), _nr.last_name(language, rng),
            "title_first_last", language=language, gender=gender,
            title_style=fmt_hint or "auto", rng=rng,
        )
    if short_label == "title_initial_last":
        return _nr.format_name(
            _nr.first_name(language, rng), _nr.last_name(language, rng),
            "title_initial_last", language=language, gender=gender, rng=rng,
        )
    if short_label == "last_first":
        return _nr.format_name(
            _nr.first_name(language, rng), _nr.last_name(language, rng),
            "last_first", rng=rng,
        )
    if short_label == "last_first_upper":
        return _nr.format_name(
            _nr.first_name(language, rng), _nr.last_name(language, rng),
            "last_first_upper", rng=rng,
        )
    if short_label == "first_initial":
        return _nr.format_name(
            _nr.first_name(language, rng), _nr.last_name(language, rng),
            "first_initial", rng=rng,
        )

    # Non-person PII
    if short_label == "address":
        return _pv.gen_address(language, fmt=fmt_hint, rng=rng)
    if short_label == "date":
        return _pv.gen_date(language, fmt=fmt_hint, rng=rng)
    if short_label == "email":
        return _pv.gen_email_ch(rng=rng)
    if short_label == "phone":
        return _pv.gen_phone_ch(fmt=fmt_hint, rng=rng)
    if short_label == "url":
        return _pv.gen_url_ch(fmt=fmt_hint, rng=rng)
    if short_label == "iban" or short_label == "account":
        return _pv.gen_iban(rng=rng)
    if short_label == "ahv":
        return _pv.gen_ahv(rng=rng)
    if short_label == "vat":
        return _pv.gen_vat(rng=rng)
    if short_label == "cc":
        return _pv.gen_credit_card(rng=rng)
    if short_label == "secret":
        return _pv.gen_secret(kind=fmt_hint, rng=rng)
    raise ValueError(f"unknown marker short_label: {short_label!r}")


def render_fragment(fragment: Fragment,
                    rng: random.Random | None = None,
                    *,
                    gender: Literal["m", "f"] | None = None,
                    ) -> tuple[str, list[Span]]:
    """Render one fragment: substitute every [[PII:...]] marker with a
    generated value, tracking output-text spans.

    The `gender` arg controls title selection for person markers; if
    None, picked randomly per-render."""
    rng = rng or random
    g = gender or rng.choice(("m", "f"))

    out_parts: list[str] = []
    spans: list[Span] = []
    cursor = 0  # position in the OUTPUT text being assembled
    pos = 0    # position in the INPUT template
    for m in _MARKER_RE.finditer(fragment.text):
        # Append literal text between previous marker and this one.
        literal = fragment.text[pos:m.start()]
        out_parts.append(literal)
        cursor += len(literal)

        short_label = m.group(1)
        fmt_hint = m.group(2)
        value = _gen_for_marker(short_label, fmt_hint,
                                fragment.language, g, rng)
        out_parts.append(value)
        spans.append(Span(start=cursor, end=cursor + len(value),
                          label=_LABEL_MAP[short_label]))
        cursor += len(value)
        pos = m.end()
    out_parts.append(fragment.text[pos:])
    return "".join(out_parts), spans


# ============================================================ COMPOSITION

@dataclass(slots=True)
class CompositionStyle:
    """How to glue greeting + body[+] + signature into one chunk."""
    # Newlines between sections. Real correspondence has 2 between
    # paragraphs (blank line); 1 inside a paragraph.
    greeting_to_body: str = "\n\n"
    body_to_body: str = "\n\n"
    body_to_signature: str = "\n\n"


def compose_email(*, greeting: Fragment, body: Fragment | list[Fragment],
                  signature: Fragment, language: str, source: str,
                  template_id_prefix: str = "email",
                  rng: random.Random | None = None,
                  style: CompositionStyle | None = None,
                  gender: Literal["m", "f"] | None = None,
                  ) -> Chunk:
    """Compose one realistic multi-paragraph email chunk.

    The composition uses the SAME gender across greeting + body +
    signature so honorifics stay consistent within one chunk.

    The full glued text is what gets emitted as the Chunk; spans
    are tracked across the splice boundaries so offsets stay valid.
    """
    rng = rng or random
    style = style or CompositionStyle()
    g = gender or rng.choice(("m", "f"))
    bodies: list[Fragment] = body if isinstance(body, list) else [body]

    parts: list[str] = []
    spans: list[Span] = []
    cursor = 0

    def _push(frag: Fragment, sep_before: str) -> None:
        nonlocal cursor
        if cursor > 0:  # don't separator before the first piece
            parts.append(sep_before)
            cursor += len(sep_before)
        text, frag_spans = render_fragment(frag, rng, gender=g)
        parts.append(text)
        for sp in frag_spans:
            spans.append(Span(start=cursor + sp.start,
                              end=cursor + sp.end,
                              label=sp.label))
        cursor += len(text)

    _push(greeting, "")
    for b in bodies:
        _push(b, style.greeting_to_body if len(parts) <= 1
              else style.body_to_body)
    _push(signature, style.body_to_signature)

    chunk_id = f"{template_id_prefix}_{uuid.uuid4().hex[:10]}"
    return Chunk(
        id=chunk_id,
        text="".join(parts),
        spans=spans,
        language=language,
        source=source,
        template_id=f"{greeting.template_id}+{bodies[0].template_id}+"
                    f"{signature.template_id}",
        meta={"gender": g,
              "n_bodies": len(bodies)},
    )


def render_standalone(fragment: Fragment, *, source: str,
                      template_id_prefix: str = "standalone",
                      rng: random.Random | None = None,
                      gender: Literal["m", "f"] | None = None,
                      ) -> Chunk:
    """Render one fragment as a standalone chunk (no composition).
    Used for short-form templates that don't combine into emails."""
    rng = rng or random
    text, spans = render_fragment(fragment, rng, gender=gender)
    return Chunk(
        id=f"{template_id_prefix}_{uuid.uuid4().hex[:10]}",
        text=text, spans=spans,
        language=fragment.language, source=source,
        template_id=fragment.template_id,
        meta={"gender": gender} if gender else {},
    )


def repeat(generator_fn, n: int) -> Iterator[Chunk]:
    """Call a generator function ``n`` times; yields each Chunk."""
    for _ in range(n):
        yield generator_fn()
